-- Voer dit pas uit nadat een beheerder via Supabase Auth is aangemaakt.
-- Vervang het UUID door het echte auth.users-id van Carolien.
-- Dit bestand wordt nooit automatisch in productie uitgevoerd.
-- insert into public.profiles(id, full_name, role)
-- values ('00000000-0000-0000-0000-000000000000', 'Carolien Ballast', 'admin');
